### PR TITLE
Add fifteen

### PR DESCRIPTION
**Pull request by bradrn**
Title should be self-explanatory…

### CODE REVIEW

**Comment by bradrn** [comment]
Er, looks like the first commit didn’t actually have the game. Sorry about that! You might want to squash when merging.

**Comment by simonmichael** [comment]
Merged as 6d44736. Thanks!

**Comment by simonmichael** [comment]
Unfortunately I think we'll have to disallow `env -S` as it's not available on GNU/Linux (at least not until coreutils 9.x).

**Comment by simonmichael** [comment]
Unfortunately I think we'll have to disallow `env -S` as it's not available on GNU/Linux (at least not until coreutils 9.x).

**Comment by simonmichael** [comment]
Opened a discussion at #25.

**Pull request closed without merging**
