### PR TITLE
Minifier and games.

### PR DESCRIPTION
**Pull request by kindaro**

### CODE REVIEW

**Comment by kindaro** [comment]
Am I on time?

**Comment by simonmichael** [comment]
Merged as 0c5e68c.

**Comment by simonmichael** [comment]
Yes, on time. 👍🏻

**Comment by simonmichael** [comment]
What's the difference between the swish variants ?
I'm wondering how to count all of these for the entry count.

**Comment by kindaro** [comment]
@simonmichael   They have different dynamics, just as `caves` and `forest` do. I wanted to show that slightly different settings create vastly different player experience. If you cannot tell the difference then I must have failed!

**Comment by simonmichael** [comment]
Will play more!

**Pull request closed without merging**
