### PR TITLE
Pong

### PR DESCRIPTION
**Pull request by gergoerdi**
- Randomize pipes
- Add Pong

### CODE REVIEW

**Comment by simonmichael** [comment]
Unfortunately I think we'll have to disallow `env -S` as it's not available on GNU/Linux (at least not until coreutils 9.x).

**Comment by simonmichael** [comment]
Opened a discussion at #25.

**Comment by simonmichael** [comment]
pong has a spare line so this is easy to fix, but I wonder why you needed `--ghc-options -threaded ` at all ? Here on mac, it seems to make no difference, and this works:
```
#!/usr/bin/env stack
-- stack script --resolver=lts-20.10 --package ansi-terminal-game
```

**Comment by gergoerdi** [comment]
Hmm, on my original version, `ansi-terminal-game` didn't work at all if not compiled with `-threaded`. I've now tried it with Stackage LTS 20.10 and indeed I don't need `-threaded` anymore.

**Pull request merged**
