### PR TITLE
Add prelude/chess

### PR DESCRIPTION
**Pull request by fizruk**
This is a very primitive implementation of chess using only Prelude. Correctness of moves is not checked. End of game is not checked. But, it is playable, in the sense that it visualises the board after every move :)

Scholar's Mate:

### CODE REVIEW

**Comment by simonmichael** [comment]
Wow! Reminds me of https://en.wikipedia.org/wiki/1K_ZX_Chess.

**Comment by fizruk** [comment]
Indeed, I did not count the shebang for some reason!

**Comment by fizruk** [comment]
> Wow! Reminds me of https://en.wikipedia.org/wiki/1K_ZX_Chess.

I wonder how feasible it is to implement full chess (with an AI) under this challenge (without resorting to something like https://hackage.haskell.org/package/chessIO).

**Comment by simonmichael** [comment]
It sounds impossible.. and yet 80x10 is not far off 1K..

**Pull request merged**
