### PR TITLE
Move games to individual folders

### PR DESCRIPTION
**Pull request by lsmor**
This commit moves games and its assets (.png/.gif) to individual folders. The script `play` still works perfectly. Feel free to discard the commit if you think the current structure is ok :)

This is related by #12 . No game has being move from one category to another though

### CODE REVIEW

**Comment by Lysxia** [comment]
There are links in the README to be fixed.

**Comment by lsmor** [comment]
@Lysxia indeed. Fixed.

**Comment by simonmichael** [comment]
Consistently give every game its own folder ? Ok let's do it. To be clear, I think we agreed the current categorisation is right so this doesn't change that ? If you wouldn't mind rebasing and possibly squashing I'll merge this tomorrow. Thanks!

**Comment by lsmor** [comment]
@simonmichael I close this because I don't know if it is possible/ how to to rebase in same PR. The same PR but with one single commit and rebased is open in #22. 

No game has change category as commented in #12 there is nothing wrong with current categorization

**Comment by Lysxia** [comment]
@lsmor  To avoid reopening PRs, you can make a normal merge commit with the main branch. The maintainer of the repository can then squash the PR in Github's UI (they might have to be enable this option in the settings).

To rebase, you have to force push (`git push --force-with-lease` (which is a bit safer than `git push --force` when more than one person may be pushing to a branch)). That is a little dangerous, hence you might prefer doing merges and leave the responsibility of squashing to repository maintainers.

**Pull request closed without merging**
